[build]
  command = "npm run build"
  publish = "dist/angular18-reto1/browser"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NETLIFY_BUILD_BASE = "/"
  NODE_VERSION = "18"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
